### ISSUE TITLE
접속 가능한 url이 있나요?

### ISSUE THREAD

**Issue by icepeng** [solarias/simplestone#1]
안녕하세요. [오리엔탈 샐러드](http://icepeng.com/home) 개발자입니다.

제가 평소에 정말 구현하고 싶었던 웹사이트인데, 어떤 기능이 구현되었는지 직접 사용해 보고 싶습니다.

**Comment by solarias** [comment]
평소 깃헙 이슈를 사용하지 않아서 답변이 늦었습니다.
심플스톤 접속 URL 말씀이시라면, https://solarias.github.io/simplestone/ 으로 접속하시면 됩니다.

그냥 내키는대로 만들어서 그리 특별한 기능은 없습니다.

**Comment by icepeng** [comment]
고맙습니다. 좋은 공부가 될것 같습니다.

**Comment by solarias** [comment]
나중에 좋은 웹사이트 만드시면 구경가도록 하겠습니다
