### ISSUE TITLE
특정 덱코드 입력이 되지 않습니다.

### ISSUE THREAD

**Issue by gdosu** [solarias/simplestone#2]
안녕하세요 먼저 좋은 사이트 만들어주셔서 감사합니다. 종종 요긴하게 사용하고 있습니다.

다음 덱코드 입력 시 덱이 만들어지지 않는데 다른 환경에서도 재연이 되는지 봐주시면 감사하겠습니다.

AAEBAZvhAwi4A/68AtPDApnHAsfTAp74AqSkA/nCAwtL4gb4B/4NgQ6HvwKbwgLKwwKixwKEsQPNvgMA

이상입니다. 좋은 하루 보내세요.

**Comment by solarias** [comment]
제보해주셔서 감사합니다.
 
덱코드를 확인해보니, 덱의 영웅이 무엇인지 파악하지 못해서 발생한 오류입니다.
영웅 ID가 61595(나그란드 가로쉬)라고 나오는데, 해당 영웅이 카드DB에 없어서 오류가 발생하였습니다.
여태까지는 스킨 영웅들도 카드DB에 있었는데 해당 영웅은 DB에서 누락되었나보네요.
 
영웅카드 파악이 안될 경우 덱에 있는 카드로 덱을 파악하도록 수정해두었습니다.
덱으로도 파악이 안되면(순수 중립카드 덱) 중립 덱 취급하도록 하긴 했는데... 그렇게까지 되지는 않겠지요.
심플스톤 업데이트를 진행하시면 해결될 겁니다.
 
 
-----Original Message-----
